### ISSUE TITLE
burger animation sitting over 'Logged in messge'

### ISSUE THREAD

**Issue by thesyaf** [CAGalaxyGuardians/McTwitter#32]
**Expected**: When user successfully logs in, a "signed in successfully" message is shown.

**Actual**: The "signed in successfully" message is covered up by the spinning burger icon.

![image](https://user-images.githubusercontent.com/23518574/31060330-6ce2898e-a75d-11e7-8d5e-7f9c5b55bdb3.png)

**Comment by moiscraycray** [comment]
This has been fixed
<img width="339" alt="screen shot 2017-10-03 at 12 55 06 am" src="https://user-images.githubusercontent.com/30609798/31080831-a0ca18e8-a7d5-11e7-927f-80a818bb28f8.png">
