### ISSUE TITLE
Move the login notice and alerts

### ISSUE THREAD

**Issue by thesyaf** [CAGalaxyGuardians/McTwitter#34]
**Expected** : if the user fails login, a message is displayed where the user will notice it. ideally close to their last action, the Login button

**Actual**: the notice/alerts are appearing at the top of the screen and below the navbar.

**Comment by moiscraycray** [comment]
This has been fixed by removing the notice/alerts from the application.html.erb in layouts. The notice/alerts have been moved to the corresponding files ie new.html.erb at the bottom
